package com.lij.dao;

import com.lij.entity.Association1;
import com.lij.entity.Association1Example;
import com.lij.entity.Association1Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Association1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    long countByExample(Association1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int deleteByExample(Association1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Association1Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int insert(Association1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int insertSelective(Association1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    List<Association1> selectByExample(Association1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    Association1 selectByPrimaryKey(Association1Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Association1 record, @Param("example") Association1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Association1 record, @Param("example") Association1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Association1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Association1 record);
}