package com.lij.dao;

import com.lij.entity.Cityarea;
import com.lij.entity.CityareaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CityareaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityarea
     *
     * @mbg.generated
     */
    long countByExample(CityareaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityarea
     *
     * @mbg.generated
     */
    int deleteByExample(CityareaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityarea
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityarea
     *
     * @mbg.generated
     */
    int insert(Cityarea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityarea
     *
     * @mbg.generated
     */
    int insertSelective(Cityarea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityarea
     *
     * @mbg.generated
     */
    List<Cityarea> selectByExample(CityareaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityarea
     *
     * @mbg.generated
     */
    Cityarea selectByPrimaryKey(String areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityarea
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Cityarea record, @Param("example") CityareaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityarea
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Cityarea record, @Param("example") CityareaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityarea
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Cityarea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityarea
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cityarea record);
}