package com.lij.dao;

import com.lij.entity.Deliveryplace;
import com.lij.entity.DeliveryplaceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeliveryplaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    long countByExample(DeliveryplaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    int deleteByExample(DeliveryplaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String depid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    int insert(Deliveryplace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    int insertSelective(Deliveryplace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    List<Deliveryplace> selectByExample(DeliveryplaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    Deliveryplace selectByPrimaryKey(String depid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Deliveryplace record, @Param("example") DeliveryplaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Deliveryplace record, @Param("example") DeliveryplaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Deliveryplace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Deliveryplace record);
}