package com.lij.dao;

import com.lij.entity.Route;
import com.lij.entity.RouteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    long countByExample(RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    int deleteByExample(RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String routeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    int insert(Route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    int insertSelective(Route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    List<Route> selectByExample(RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    Route selectByPrimaryKey(String routeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Route record, @Param("example") RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Route record, @Param("example") RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Route record);
}