package com.lij.entity;

import java.util.ArrayList;
import java.util.List;

public class Association1Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table association_1
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table association_1
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table association_1
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    public Association1Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table association_1
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrdOrderidIsNull() {
            addCriterion("Ord_orderID is null");
            return (Criteria) this;
        }

        public Criteria andOrdOrderidIsNotNull() {
            addCriterion("Ord_orderID is not null");
            return (Criteria) this;
        }

        public Criteria andOrdOrderidEqualTo(String value) {
            addCriterion("Ord_orderID =", value, "ordOrderid");
            return (Criteria) this;
        }

        public Criteria andOrdOrderidNotEqualTo(String value) {
            addCriterion("Ord_orderID <>", value, "ordOrderid");
            return (Criteria) this;
        }

        public Criteria andOrdOrderidGreaterThan(String value) {
            addCriterion("Ord_orderID >", value, "ordOrderid");
            return (Criteria) this;
        }

        public Criteria andOrdOrderidGreaterThanOrEqualTo(String value) {
            addCriterion("Ord_orderID >=", value, "ordOrderid");
            return (Criteria) this;
        }

        public Criteria andOrdOrderidLessThan(String value) {
            addCriterion("Ord_orderID <", value, "ordOrderid");
            return (Criteria) this;
        }

        public Criteria andOrdOrderidLessThanOrEqualTo(String value) {
            addCriterion("Ord_orderID <=", value, "ordOrderid");
            return (Criteria) this;
        }

        public Criteria andOrdOrderidLike(String value) {
            addCriterion("Ord_orderID like", value, "ordOrderid");
            return (Criteria) this;
        }

        public Criteria andOrdOrderidNotLike(String value) {
            addCriterion("Ord_orderID not like", value, "ordOrderid");
            return (Criteria) this;
        }

        public Criteria andOrdOrderidIn(List<String> values) {
            addCriterion("Ord_orderID in", values, "ordOrderid");
            return (Criteria) this;
        }

        public Criteria andOrdOrderidNotIn(List<String> values) {
            addCriterion("Ord_orderID not in", values, "ordOrderid");
            return (Criteria) this;
        }

        public Criteria andOrdOrderidBetween(String value1, String value2) {
            addCriterion("Ord_orderID between", value1, value2, "ordOrderid");
            return (Criteria) this;
        }

        public Criteria andOrdOrderidNotBetween(String value1, String value2) {
            addCriterion("Ord_orderID not between", value1, value2, "ordOrderid");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryreceiptidIsNull() {
            addCriterion("Del_deliveryReceiptID is null");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryreceiptidIsNotNull() {
            addCriterion("Del_deliveryReceiptID is not null");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryreceiptidEqualTo(String value) {
            addCriterion("Del_deliveryReceiptID =", value, "delDeliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryreceiptidNotEqualTo(String value) {
            addCriterion("Del_deliveryReceiptID <>", value, "delDeliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryreceiptidGreaterThan(String value) {
            addCriterion("Del_deliveryReceiptID >", value, "delDeliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryreceiptidGreaterThanOrEqualTo(String value) {
            addCriterion("Del_deliveryReceiptID >=", value, "delDeliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryreceiptidLessThan(String value) {
            addCriterion("Del_deliveryReceiptID <", value, "delDeliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryreceiptidLessThanOrEqualTo(String value) {
            addCriterion("Del_deliveryReceiptID <=", value, "delDeliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryreceiptidLike(String value) {
            addCriterion("Del_deliveryReceiptID like", value, "delDeliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryreceiptidNotLike(String value) {
            addCriterion("Del_deliveryReceiptID not like", value, "delDeliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryreceiptidIn(List<String> values) {
            addCriterion("Del_deliveryReceiptID in", values, "delDeliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryreceiptidNotIn(List<String> values) {
            addCriterion("Del_deliveryReceiptID not in", values, "delDeliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryreceiptidBetween(String value1, String value2) {
            addCriterion("Del_deliveryReceiptID between", value1, value2, "delDeliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryreceiptidNotBetween(String value1, String value2) {
            addCriterion("Del_deliveryReceiptID not between", value1, value2, "delDeliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderID is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(String value) {
            addCriterion("orderID =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(String value) {
            addCriterion("orderID <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(String value) {
            addCriterion("orderID >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(String value) {
            addCriterion("orderID >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(String value) {
            addCriterion("orderID <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(String value) {
            addCriterion("orderID <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLike(String value) {
            addCriterion("orderID like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotLike(String value) {
            addCriterion("orderID not like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<String> values) {
            addCriterion("orderID in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<String> values) {
            addCriterion("orderID not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(String value1, String value2) {
            addCriterion("orderID between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(String value1, String value2) {
            addCriterion("orderID not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andDeliveryreceiptidIsNull() {
            addCriterion("deliveryReceiptID is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryreceiptidIsNotNull() {
            addCriterion("deliveryReceiptID is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryreceiptidEqualTo(String value) {
            addCriterion("deliveryReceiptID =", value, "deliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDeliveryreceiptidNotEqualTo(String value) {
            addCriterion("deliveryReceiptID <>", value, "deliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDeliveryreceiptidGreaterThan(String value) {
            addCriterion("deliveryReceiptID >", value, "deliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDeliveryreceiptidGreaterThanOrEqualTo(String value) {
            addCriterion("deliveryReceiptID >=", value, "deliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDeliveryreceiptidLessThan(String value) {
            addCriterion("deliveryReceiptID <", value, "deliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDeliveryreceiptidLessThanOrEqualTo(String value) {
            addCriterion("deliveryReceiptID <=", value, "deliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDeliveryreceiptidLike(String value) {
            addCriterion("deliveryReceiptID like", value, "deliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDeliveryreceiptidNotLike(String value) {
            addCriterion("deliveryReceiptID not like", value, "deliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDeliveryreceiptidIn(List<String> values) {
            addCriterion("deliveryReceiptID in", values, "deliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDeliveryreceiptidNotIn(List<String> values) {
            addCriterion("deliveryReceiptID not in", values, "deliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDeliveryreceiptidBetween(String value1, String value2) {
            addCriterion("deliveryReceiptID between", value1, value2, "deliveryreceiptid");
            return (Criteria) this;
        }

        public Criteria andDeliveryreceiptidNotBetween(String value1, String value2) {
            addCriterion("deliveryReceiptID not between", value1, value2, "deliveryreceiptid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table association_1
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table association_1
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}