package com.lij.entity;

public class Association1 extends Association1Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column association_1.orderID
     *
     * @mbg.generated
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column association_1.deliveryReceiptID
     *
     * @mbg.generated
     */
    private String deliveryreceiptid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column association_1.orderID
     *
     * @return the value of association_1.orderID
     *
     * @mbg.generated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column association_1.orderID
     *
     * @param orderid the value for association_1.orderID
     *
     * @mbg.generated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column association_1.deliveryReceiptID
     *
     * @return the value of association_1.deliveryReceiptID
     *
     * @mbg.generated
     */
    public String getDeliveryreceiptid() {
        return deliveryreceiptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column association_1.deliveryReceiptID
     *
     * @param deliveryreceiptid the value for association_1.deliveryReceiptID
     *
     * @mbg.generated
     */
    public void setDeliveryreceiptid(String deliveryreceiptid) {
        this.deliveryreceiptid = deliveryreceiptid == null ? null : deliveryreceiptid.trim();
    }
}