package com.lij.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DeliveryrangeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    public DeliveryrangeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRangeidIsNull() {
            addCriterion("rangeID is null");
            return (Criteria) this;
        }

        public Criteria andRangeidIsNotNull() {
            addCriterion("rangeID is not null");
            return (Criteria) this;
        }

        public Criteria andRangeidEqualTo(String value) {
            addCriterion("rangeID =", value, "rangeid");
            return (Criteria) this;
        }

        public Criteria andRangeidNotEqualTo(String value) {
            addCriterion("rangeID <>", value, "rangeid");
            return (Criteria) this;
        }

        public Criteria andRangeidGreaterThan(String value) {
            addCriterion("rangeID >", value, "rangeid");
            return (Criteria) this;
        }

        public Criteria andRangeidGreaterThanOrEqualTo(String value) {
            addCriterion("rangeID >=", value, "rangeid");
            return (Criteria) this;
        }

        public Criteria andRangeidLessThan(String value) {
            addCriterion("rangeID <", value, "rangeid");
            return (Criteria) this;
        }

        public Criteria andRangeidLessThanOrEqualTo(String value) {
            addCriterion("rangeID <=", value, "rangeid");
            return (Criteria) this;
        }

        public Criteria andRangeidLike(String value) {
            addCriterion("rangeID like", value, "rangeid");
            return (Criteria) this;
        }

        public Criteria andRangeidNotLike(String value) {
            addCriterion("rangeID not like", value, "rangeid");
            return (Criteria) this;
        }

        public Criteria andRangeidIn(List<String> values) {
            addCriterion("rangeID in", values, "rangeid");
            return (Criteria) this;
        }

        public Criteria andRangeidNotIn(List<String> values) {
            addCriterion("rangeID not in", values, "rangeid");
            return (Criteria) this;
        }

        public Criteria andRangeidBetween(String value1, String value2) {
            addCriterion("rangeID between", value1, value2, "rangeid");
            return (Criteria) this;
        }

        public Criteria andRangeidNotBetween(String value1, String value2) {
            addCriterion("rangeID not between", value1, value2, "rangeid");
            return (Criteria) this;
        }

        public Criteria andDepidIsNull() {
            addCriterion("dePID is null");
            return (Criteria) this;
        }

        public Criteria andDepidIsNotNull() {
            addCriterion("dePID is not null");
            return (Criteria) this;
        }

        public Criteria andDepidEqualTo(String value) {
            addCriterion("dePID =", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidNotEqualTo(String value) {
            addCriterion("dePID <>", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidGreaterThan(String value) {
            addCriterion("dePID >", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidGreaterThanOrEqualTo(String value) {
            addCriterion("dePID >=", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidLessThan(String value) {
            addCriterion("dePID <", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidLessThanOrEqualTo(String value) {
            addCriterion("dePID <=", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidLike(String value) {
            addCriterion("dePID like", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidNotLike(String value) {
            addCriterion("dePID not like", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidIn(List<String> values) {
            addCriterion("dePID in", values, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidNotIn(List<String> values) {
            addCriterion("dePID not in", values, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidBetween(String value1, String value2) {
            addCriterion("dePID between", value1, value2, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidNotBetween(String value1, String value2) {
            addCriterion("dePID not between", value1, value2, "depid");
            return (Criteria) this;
        }

        public Criteria andAreaidIsNull() {
            addCriterion("areaID is null");
            return (Criteria) this;
        }

        public Criteria andAreaidIsNotNull() {
            addCriterion("areaID is not null");
            return (Criteria) this;
        }

        public Criteria andAreaidEqualTo(String value) {
            addCriterion("areaID =", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotEqualTo(String value) {
            addCriterion("areaID <>", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidGreaterThan(String value) {
            addCriterion("areaID >", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidGreaterThanOrEqualTo(String value) {
            addCriterion("areaID >=", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidLessThan(String value) {
            addCriterion("areaID <", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidLessThanOrEqualTo(String value) {
            addCriterion("areaID <=", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidLike(String value) {
            addCriterion("areaID like", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotLike(String value) {
            addCriterion("areaID not like", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidIn(List<String> values) {
            addCriterion("areaID in", values, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotIn(List<String> values) {
            addCriterion("areaID not in", values, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidBetween(String value1, String value2) {
            addCriterion("areaID between", value1, value2, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotBetween(String value1, String value2) {
            addCriterion("areaID not between", value1, value2, "areaid");
            return (Criteria) this;
        }

        public Criteria andRangenameIsNull() {
            addCriterion("rangeName is null");
            return (Criteria) this;
        }

        public Criteria andRangenameIsNotNull() {
            addCriterion("rangeName is not null");
            return (Criteria) this;
        }

        public Criteria andRangenameEqualTo(String value) {
            addCriterion("rangeName =", value, "rangename");
            return (Criteria) this;
        }

        public Criteria andRangenameNotEqualTo(String value) {
            addCriterion("rangeName <>", value, "rangename");
            return (Criteria) this;
        }

        public Criteria andRangenameGreaterThan(String value) {
            addCriterion("rangeName >", value, "rangename");
            return (Criteria) this;
        }

        public Criteria andRangenameGreaterThanOrEqualTo(String value) {
            addCriterion("rangeName >=", value, "rangename");
            return (Criteria) this;
        }

        public Criteria andRangenameLessThan(String value) {
            addCriterion("rangeName <", value, "rangename");
            return (Criteria) this;
        }

        public Criteria andRangenameLessThanOrEqualTo(String value) {
            addCriterion("rangeName <=", value, "rangename");
            return (Criteria) this;
        }

        public Criteria andRangenameLike(String value) {
            addCriterion("rangeName like", value, "rangename");
            return (Criteria) this;
        }

        public Criteria andRangenameNotLike(String value) {
            addCriterion("rangeName not like", value, "rangename");
            return (Criteria) this;
        }

        public Criteria andRangenameIn(List<String> values) {
            addCriterion("rangeName in", values, "rangename");
            return (Criteria) this;
        }

        public Criteria andRangenameNotIn(List<String> values) {
            addCriterion("rangeName not in", values, "rangename");
            return (Criteria) this;
        }

        public Criteria andRangenameBetween(String value1, String value2) {
            addCriterion("rangeName between", value1, value2, "rangename");
            return (Criteria) this;
        }

        public Criteria andRangenameNotBetween(String value1, String value2) {
            addCriterion("rangeName not between", value1, value2, "rangename");
            return (Criteria) this;
        }

        public Criteria andDeliveiypriceIsNull() {
            addCriterion("deliveiyPrice is null");
            return (Criteria) this;
        }

        public Criteria andDeliveiypriceIsNotNull() {
            addCriterion("deliveiyPrice is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveiypriceEqualTo(BigDecimal value) {
            addCriterion("deliveiyPrice =", value, "deliveiyprice");
            return (Criteria) this;
        }

        public Criteria andDeliveiypriceNotEqualTo(BigDecimal value) {
            addCriterion("deliveiyPrice <>", value, "deliveiyprice");
            return (Criteria) this;
        }

        public Criteria andDeliveiypriceGreaterThan(BigDecimal value) {
            addCriterion("deliveiyPrice >", value, "deliveiyprice");
            return (Criteria) this;
        }

        public Criteria andDeliveiypriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("deliveiyPrice >=", value, "deliveiyprice");
            return (Criteria) this;
        }

        public Criteria andDeliveiypriceLessThan(BigDecimal value) {
            addCriterion("deliveiyPrice <", value, "deliveiyprice");
            return (Criteria) this;
        }

        public Criteria andDeliveiypriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("deliveiyPrice <=", value, "deliveiyprice");
            return (Criteria) this;
        }

        public Criteria andDeliveiypriceIn(List<BigDecimal> values) {
            addCriterion("deliveiyPrice in", values, "deliveiyprice");
            return (Criteria) this;
        }

        public Criteria andDeliveiypriceNotIn(List<BigDecimal> values) {
            addCriterion("deliveiyPrice not in", values, "deliveiyprice");
            return (Criteria) this;
        }

        public Criteria andDeliveiypriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("deliveiyPrice between", value1, value2, "deliveiyprice");
            return (Criteria) this;
        }

        public Criteria andDeliveiypriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("deliveiyPrice not between", value1, value2, "deliveiyprice");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("Comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("Comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("Comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("Comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("Comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("Comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("Comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("Comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("Comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("Comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("Comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("Comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("Comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("Comment not between", value1, value2, "comment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deliveryrange
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}