package com.lij.entity;

import java.util.ArrayList;
import java.util.List;

public class DeliveryplaceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    public DeliveryplaceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDepidIsNull() {
            addCriterion("dePID is null");
            return (Criteria) this;
        }

        public Criteria andDepidIsNotNull() {
            addCriterion("dePID is not null");
            return (Criteria) this;
        }

        public Criteria andDepidEqualTo(String value) {
            addCriterion("dePID =", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidNotEqualTo(String value) {
            addCriterion("dePID <>", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidGreaterThan(String value) {
            addCriterion("dePID >", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidGreaterThanOrEqualTo(String value) {
            addCriterion("dePID >=", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidLessThan(String value) {
            addCriterion("dePID <", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidLessThanOrEqualTo(String value) {
            addCriterion("dePID <=", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidLike(String value) {
            addCriterion("dePID like", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidNotLike(String value) {
            addCriterion("dePID not like", value, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidIn(List<String> values) {
            addCriterion("dePID in", values, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidNotIn(List<String> values) {
            addCriterion("dePID not in", values, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidBetween(String value1, String value2) {
            addCriterion("dePID between", value1, value2, "depid");
            return (Criteria) this;
        }

        public Criteria andDepidNotBetween(String value1, String value2) {
            addCriterion("dePID not between", value1, value2, "depid");
            return (Criteria) this;
        }

        public Criteria andMgidIsNull() {
            addCriterion("mgID is null");
            return (Criteria) this;
        }

        public Criteria andMgidIsNotNull() {
            addCriterion("mgID is not null");
            return (Criteria) this;
        }

        public Criteria andMgidEqualTo(String value) {
            addCriterion("mgID =", value, "mgid");
            return (Criteria) this;
        }

        public Criteria andMgidNotEqualTo(String value) {
            addCriterion("mgID <>", value, "mgid");
            return (Criteria) this;
        }

        public Criteria andMgidGreaterThan(String value) {
            addCriterion("mgID >", value, "mgid");
            return (Criteria) this;
        }

        public Criteria andMgidGreaterThanOrEqualTo(String value) {
            addCriterion("mgID >=", value, "mgid");
            return (Criteria) this;
        }

        public Criteria andMgidLessThan(String value) {
            addCriterion("mgID <", value, "mgid");
            return (Criteria) this;
        }

        public Criteria andMgidLessThanOrEqualTo(String value) {
            addCriterion("mgID <=", value, "mgid");
            return (Criteria) this;
        }

        public Criteria andMgidLike(String value) {
            addCriterion("mgID like", value, "mgid");
            return (Criteria) this;
        }

        public Criteria andMgidNotLike(String value) {
            addCriterion("mgID not like", value, "mgid");
            return (Criteria) this;
        }

        public Criteria andMgidIn(List<String> values) {
            addCriterion("mgID in", values, "mgid");
            return (Criteria) this;
        }

        public Criteria andMgidNotIn(List<String> values) {
            addCriterion("mgID not in", values, "mgid");
            return (Criteria) this;
        }

        public Criteria andMgidBetween(String value1, String value2) {
            addCriterion("mgID between", value1, value2, "mgid");
            return (Criteria) this;
        }

        public Criteria andMgidNotBetween(String value1, String value2) {
            addCriterion("mgID not between", value1, value2, "mgid");
            return (Criteria) this;
        }

        public Criteria andDepnameIsNull() {
            addCriterion("dePNAme is null");
            return (Criteria) this;
        }

        public Criteria andDepnameIsNotNull() {
            addCriterion("dePNAme is not null");
            return (Criteria) this;
        }

        public Criteria andDepnameEqualTo(String value) {
            addCriterion("dePNAme =", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameNotEqualTo(String value) {
            addCriterion("dePNAme <>", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameGreaterThan(String value) {
            addCriterion("dePNAme >", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameGreaterThanOrEqualTo(String value) {
            addCriterion("dePNAme >=", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameLessThan(String value) {
            addCriterion("dePNAme <", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameLessThanOrEqualTo(String value) {
            addCriterion("dePNAme <=", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameLike(String value) {
            addCriterion("dePNAme like", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameNotLike(String value) {
            addCriterion("dePNAme not like", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameIn(List<String> values) {
            addCriterion("dePNAme in", values, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameNotIn(List<String> values) {
            addCriterion("dePNAme not in", values, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameBetween(String value1, String value2) {
            addCriterion("dePNAme between", value1, value2, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameNotBetween(String value1, String value2) {
            addCriterion("dePNAme not between", value1, value2, "depname");
            return (Criteria) this;
        }

        public Criteria andProvincenameIsNull() {
            addCriterion("provinceName is null");
            return (Criteria) this;
        }

        public Criteria andProvincenameIsNotNull() {
            addCriterion("provinceName is not null");
            return (Criteria) this;
        }

        public Criteria andProvincenameEqualTo(String value) {
            addCriterion("provinceName =", value, "provincename");
            return (Criteria) this;
        }

        public Criteria andProvincenameNotEqualTo(String value) {
            addCriterion("provinceName <>", value, "provincename");
            return (Criteria) this;
        }

        public Criteria andProvincenameGreaterThan(String value) {
            addCriterion("provinceName >", value, "provincename");
            return (Criteria) this;
        }

        public Criteria andProvincenameGreaterThanOrEqualTo(String value) {
            addCriterion("provinceName >=", value, "provincename");
            return (Criteria) this;
        }

        public Criteria andProvincenameLessThan(String value) {
            addCriterion("provinceName <", value, "provincename");
            return (Criteria) this;
        }

        public Criteria andProvincenameLessThanOrEqualTo(String value) {
            addCriterion("provinceName <=", value, "provincename");
            return (Criteria) this;
        }

        public Criteria andProvincenameLike(String value) {
            addCriterion("provinceName like", value, "provincename");
            return (Criteria) this;
        }

        public Criteria andProvincenameNotLike(String value) {
            addCriterion("provinceName not like", value, "provincename");
            return (Criteria) this;
        }

        public Criteria andProvincenameIn(List<String> values) {
            addCriterion("provinceName in", values, "provincename");
            return (Criteria) this;
        }

        public Criteria andProvincenameNotIn(List<String> values) {
            addCriterion("provinceName not in", values, "provincename");
            return (Criteria) this;
        }

        public Criteria andProvincenameBetween(String value1, String value2) {
            addCriterion("provinceName between", value1, value2, "provincename");
            return (Criteria) this;
        }

        public Criteria andProvincenameNotBetween(String value1, String value2) {
            addCriterion("provinceName not between", value1, value2, "provincename");
            return (Criteria) this;
        }

        public Criteria andCitynameIsNull() {
            addCriterion("cityName is null");
            return (Criteria) this;
        }

        public Criteria andCitynameIsNotNull() {
            addCriterion("cityName is not null");
            return (Criteria) this;
        }

        public Criteria andCitynameEqualTo(String value) {
            addCriterion("cityName =", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameNotEqualTo(String value) {
            addCriterion("cityName <>", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameGreaterThan(String value) {
            addCriterion("cityName >", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameGreaterThanOrEqualTo(String value) {
            addCriterion("cityName >=", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameLessThan(String value) {
            addCriterion("cityName <", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameLessThanOrEqualTo(String value) {
            addCriterion("cityName <=", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameLike(String value) {
            addCriterion("cityName like", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameNotLike(String value) {
            addCriterion("cityName not like", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameIn(List<String> values) {
            addCriterion("cityName in", values, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameNotIn(List<String> values) {
            addCriterion("cityName not in", values, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameBetween(String value1, String value2) {
            addCriterion("cityName between", value1, value2, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameNotBetween(String value1, String value2) {
            addCriterion("cityName not between", value1, value2, "cityname");
            return (Criteria) this;
        }

        public Criteria andMgnameIsNull() {
            addCriterion("mgName is null");
            return (Criteria) this;
        }

        public Criteria andMgnameIsNotNull() {
            addCriterion("mgName is not null");
            return (Criteria) this;
        }

        public Criteria andMgnameEqualTo(String value) {
            addCriterion("mgName =", value, "mgname");
            return (Criteria) this;
        }

        public Criteria andMgnameNotEqualTo(String value) {
            addCriterion("mgName <>", value, "mgname");
            return (Criteria) this;
        }

        public Criteria andMgnameGreaterThan(String value) {
            addCriterion("mgName >", value, "mgname");
            return (Criteria) this;
        }

        public Criteria andMgnameGreaterThanOrEqualTo(String value) {
            addCriterion("mgName >=", value, "mgname");
            return (Criteria) this;
        }

        public Criteria andMgnameLessThan(String value) {
            addCriterion("mgName <", value, "mgname");
            return (Criteria) this;
        }

        public Criteria andMgnameLessThanOrEqualTo(String value) {
            addCriterion("mgName <=", value, "mgname");
            return (Criteria) this;
        }

        public Criteria andMgnameLike(String value) {
            addCriterion("mgName like", value, "mgname");
            return (Criteria) this;
        }

        public Criteria andMgnameNotLike(String value) {
            addCriterion("mgName not like", value, "mgname");
            return (Criteria) this;
        }

        public Criteria andMgnameIn(List<String> values) {
            addCriterion("mgName in", values, "mgname");
            return (Criteria) this;
        }

        public Criteria andMgnameNotIn(List<String> values) {
            addCriterion("mgName not in", values, "mgname");
            return (Criteria) this;
        }

        public Criteria andMgnameBetween(String value1, String value2) {
            addCriterion("mgName between", value1, value2, "mgname");
            return (Criteria) this;
        }

        public Criteria andMgnameNotBetween(String value1, String value2) {
            addCriterion("mgName not between", value1, value2, "mgname");
            return (Criteria) this;
        }

        public Criteria andDeptelIsNull() {
            addCriterion("dePTel is null");
            return (Criteria) this;
        }

        public Criteria andDeptelIsNotNull() {
            addCriterion("dePTel is not null");
            return (Criteria) this;
        }

        public Criteria andDeptelEqualTo(String value) {
            addCriterion("dePTel =", value, "deptel");
            return (Criteria) this;
        }

        public Criteria andDeptelNotEqualTo(String value) {
            addCriterion("dePTel <>", value, "deptel");
            return (Criteria) this;
        }

        public Criteria andDeptelGreaterThan(String value) {
            addCriterion("dePTel >", value, "deptel");
            return (Criteria) this;
        }

        public Criteria andDeptelGreaterThanOrEqualTo(String value) {
            addCriterion("dePTel >=", value, "deptel");
            return (Criteria) this;
        }

        public Criteria andDeptelLessThan(String value) {
            addCriterion("dePTel <", value, "deptel");
            return (Criteria) this;
        }

        public Criteria andDeptelLessThanOrEqualTo(String value) {
            addCriterion("dePTel <=", value, "deptel");
            return (Criteria) this;
        }

        public Criteria andDeptelLike(String value) {
            addCriterion("dePTel like", value, "deptel");
            return (Criteria) this;
        }

        public Criteria andDeptelNotLike(String value) {
            addCriterion("dePTel not like", value, "deptel");
            return (Criteria) this;
        }

        public Criteria andDeptelIn(List<String> values) {
            addCriterion("dePTel in", values, "deptel");
            return (Criteria) this;
        }

        public Criteria andDeptelNotIn(List<String> values) {
            addCriterion("dePTel not in", values, "deptel");
            return (Criteria) this;
        }

        public Criteria andDeptelBetween(String value1, String value2) {
            addCriterion("dePTel between", value1, value2, "deptel");
            return (Criteria) this;
        }

        public Criteria andDeptelNotBetween(String value1, String value2) {
            addCriterion("dePTel not between", value1, value2, "deptel");
            return (Criteria) this;
        }

        public Criteria andDepaddrIsNull() {
            addCriterion("dePAddr is null");
            return (Criteria) this;
        }

        public Criteria andDepaddrIsNotNull() {
            addCriterion("dePAddr is not null");
            return (Criteria) this;
        }

        public Criteria andDepaddrEqualTo(String value) {
            addCriterion("dePAddr =", value, "depaddr");
            return (Criteria) this;
        }

        public Criteria andDepaddrNotEqualTo(String value) {
            addCriterion("dePAddr <>", value, "depaddr");
            return (Criteria) this;
        }

        public Criteria andDepaddrGreaterThan(String value) {
            addCriterion("dePAddr >", value, "depaddr");
            return (Criteria) this;
        }

        public Criteria andDepaddrGreaterThanOrEqualTo(String value) {
            addCriterion("dePAddr >=", value, "depaddr");
            return (Criteria) this;
        }

        public Criteria andDepaddrLessThan(String value) {
            addCriterion("dePAddr <", value, "depaddr");
            return (Criteria) this;
        }

        public Criteria andDepaddrLessThanOrEqualTo(String value) {
            addCriterion("dePAddr <=", value, "depaddr");
            return (Criteria) this;
        }

        public Criteria andDepaddrLike(String value) {
            addCriterion("dePAddr like", value, "depaddr");
            return (Criteria) this;
        }

        public Criteria andDepaddrNotLike(String value) {
            addCriterion("dePAddr not like", value, "depaddr");
            return (Criteria) this;
        }

        public Criteria andDepaddrIn(List<String> values) {
            addCriterion("dePAddr in", values, "depaddr");
            return (Criteria) this;
        }

        public Criteria andDepaddrNotIn(List<String> values) {
            addCriterion("dePAddr not in", values, "depaddr");
            return (Criteria) this;
        }

        public Criteria andDepaddrBetween(String value1, String value2) {
            addCriterion("dePAddr between", value1, value2, "depaddr");
            return (Criteria) this;
        }

        public Criteria andDepaddrNotBetween(String value1, String value2) {
            addCriterion("dePAddr not between", value1, value2, "depaddr");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("Comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("Comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("Comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("Comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("Comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("Comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("Comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("Comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("Comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("Comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("Comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("Comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("Comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("Comment not between", value1, value2, "comment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deliveryplace
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deliveryplace
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}