package com.lij.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeliveryreceiptExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    public DeliveryreceiptExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDelivervreceiptidIsNull() {
            addCriterion("delivervReceiptID is null");
            return (Criteria) this;
        }

        public Criteria andDelivervreceiptidIsNotNull() {
            addCriterion("delivervReceiptID is not null");
            return (Criteria) this;
        }

        public Criteria andDelivervreceiptidEqualTo(String value) {
            addCriterion("delivervReceiptID =", value, "delivervreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelivervreceiptidNotEqualTo(String value) {
            addCriterion("delivervReceiptID <>", value, "delivervreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelivervreceiptidGreaterThan(String value) {
            addCriterion("delivervReceiptID >", value, "delivervreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelivervreceiptidGreaterThanOrEqualTo(String value) {
            addCriterion("delivervReceiptID >=", value, "delivervreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelivervreceiptidLessThan(String value) {
            addCriterion("delivervReceiptID <", value, "delivervreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelivervreceiptidLessThanOrEqualTo(String value) {
            addCriterion("delivervReceiptID <=", value, "delivervreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelivervreceiptidLike(String value) {
            addCriterion("delivervReceiptID like", value, "delivervreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelivervreceiptidNotLike(String value) {
            addCriterion("delivervReceiptID not like", value, "delivervreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelivervreceiptidIn(List<String> values) {
            addCriterion("delivervReceiptID in", values, "delivervreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelivervreceiptidNotIn(List<String> values) {
            addCriterion("delivervReceiptID not in", values, "delivervreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelivervreceiptidBetween(String value1, String value2) {
            addCriterion("delivervReceiptID between", value1, value2, "delivervreceiptid");
            return (Criteria) this;
        }

        public Criteria andDelivervreceiptidNotBetween(String value1, String value2) {
            addCriterion("delivervReceiptID not between", value1, value2, "delivervreceiptid");
            return (Criteria) this;
        }

        public Criteria andStartcityIsNull() {
            addCriterion("startCity is null");
            return (Criteria) this;
        }

        public Criteria andStartcityIsNotNull() {
            addCriterion("startCity is not null");
            return (Criteria) this;
        }

        public Criteria andStartcityEqualTo(String value) {
            addCriterion("startCity =", value, "startcity");
            return (Criteria) this;
        }

        public Criteria andStartcityNotEqualTo(String value) {
            addCriterion("startCity <>", value, "startcity");
            return (Criteria) this;
        }

        public Criteria andStartcityGreaterThan(String value) {
            addCriterion("startCity >", value, "startcity");
            return (Criteria) this;
        }

        public Criteria andStartcityGreaterThanOrEqualTo(String value) {
            addCriterion("startCity >=", value, "startcity");
            return (Criteria) this;
        }

        public Criteria andStartcityLessThan(String value) {
            addCriterion("startCity <", value, "startcity");
            return (Criteria) this;
        }

        public Criteria andStartcityLessThanOrEqualTo(String value) {
            addCriterion("startCity <=", value, "startcity");
            return (Criteria) this;
        }

        public Criteria andStartcityLike(String value) {
            addCriterion("startCity like", value, "startcity");
            return (Criteria) this;
        }

        public Criteria andStartcityNotLike(String value) {
            addCriterion("startCity not like", value, "startcity");
            return (Criteria) this;
        }

        public Criteria andStartcityIn(List<String> values) {
            addCriterion("startCity in", values, "startcity");
            return (Criteria) this;
        }

        public Criteria andStartcityNotIn(List<String> values) {
            addCriterion("startCity not in", values, "startcity");
            return (Criteria) this;
        }

        public Criteria andStartcityBetween(String value1, String value2) {
            addCriterion("startCity between", value1, value2, "startcity");
            return (Criteria) this;
        }

        public Criteria andStartcityNotBetween(String value1, String value2) {
            addCriterion("startCity not between", value1, value2, "startcity");
            return (Criteria) this;
        }

        public Criteria andEndcityIsNull() {
            addCriterion("endCity is null");
            return (Criteria) this;
        }

        public Criteria andEndcityIsNotNull() {
            addCriterion("endCity is not null");
            return (Criteria) this;
        }

        public Criteria andEndcityEqualTo(String value) {
            addCriterion("endCity =", value, "endcity");
            return (Criteria) this;
        }

        public Criteria andEndcityNotEqualTo(String value) {
            addCriterion("endCity <>", value, "endcity");
            return (Criteria) this;
        }

        public Criteria andEndcityGreaterThan(String value) {
            addCriterion("endCity >", value, "endcity");
            return (Criteria) this;
        }

        public Criteria andEndcityGreaterThanOrEqualTo(String value) {
            addCriterion("endCity >=", value, "endcity");
            return (Criteria) this;
        }

        public Criteria andEndcityLessThan(String value) {
            addCriterion("endCity <", value, "endcity");
            return (Criteria) this;
        }

        public Criteria andEndcityLessThanOrEqualTo(String value) {
            addCriterion("endCity <=", value, "endcity");
            return (Criteria) this;
        }

        public Criteria andEndcityLike(String value) {
            addCriterion("endCity like", value, "endcity");
            return (Criteria) this;
        }

        public Criteria andEndcityNotLike(String value) {
            addCriterion("endCity not like", value, "endcity");
            return (Criteria) this;
        }

        public Criteria andEndcityIn(List<String> values) {
            addCriterion("endCity in", values, "endcity");
            return (Criteria) this;
        }

        public Criteria andEndcityNotIn(List<String> values) {
            addCriterion("endCity not in", values, "endcity");
            return (Criteria) this;
        }

        public Criteria andEndcityBetween(String value1, String value2) {
            addCriterion("endCity between", value1, value2, "endcity");
            return (Criteria) this;
        }

        public Criteria andEndcityNotBetween(String value1, String value2) {
            addCriterion("endCity not between", value1, value2, "endcity");
            return (Criteria) this;
        }

        public Criteria andMidcityIsNull() {
            addCriterion("midCity is null");
            return (Criteria) this;
        }

        public Criteria andMidcityIsNotNull() {
            addCriterion("midCity is not null");
            return (Criteria) this;
        }

        public Criteria andMidcityEqualTo(String value) {
            addCriterion("midCity =", value, "midcity");
            return (Criteria) this;
        }

        public Criteria andMidcityNotEqualTo(String value) {
            addCriterion("midCity <>", value, "midcity");
            return (Criteria) this;
        }

        public Criteria andMidcityGreaterThan(String value) {
            addCriterion("midCity >", value, "midcity");
            return (Criteria) this;
        }

        public Criteria andMidcityGreaterThanOrEqualTo(String value) {
            addCriterion("midCity >=", value, "midcity");
            return (Criteria) this;
        }

        public Criteria andMidcityLessThan(String value) {
            addCriterion("midCity <", value, "midcity");
            return (Criteria) this;
        }

        public Criteria andMidcityLessThanOrEqualTo(String value) {
            addCriterion("midCity <=", value, "midcity");
            return (Criteria) this;
        }

        public Criteria andMidcityLike(String value) {
            addCriterion("midCity like", value, "midcity");
            return (Criteria) this;
        }

        public Criteria andMidcityNotLike(String value) {
            addCriterion("midCity not like", value, "midcity");
            return (Criteria) this;
        }

        public Criteria andMidcityIn(List<String> values) {
            addCriterion("midCity in", values, "midcity");
            return (Criteria) this;
        }

        public Criteria andMidcityNotIn(List<String> values) {
            addCriterion("midCity not in", values, "midcity");
            return (Criteria) this;
        }

        public Criteria andMidcityBetween(String value1, String value2) {
            addCriterion("midCity between", value1, value2, "midcity");
            return (Criteria) this;
        }

        public Criteria andMidcityNotBetween(String value1, String value2) {
            addCriterion("midCity not between", value1, value2, "midcity");
            return (Criteria) this;
        }

        public Criteria andMakedtaeIsNull() {
            addCriterion("makeDtae is null");
            return (Criteria) this;
        }

        public Criteria andMakedtaeIsNotNull() {
            addCriterion("makeDtae is not null");
            return (Criteria) this;
        }

        public Criteria andMakedtaeEqualTo(Date value) {
            addCriterion("makeDtae =", value, "makedtae");
            return (Criteria) this;
        }

        public Criteria andMakedtaeNotEqualTo(Date value) {
            addCriterion("makeDtae <>", value, "makedtae");
            return (Criteria) this;
        }

        public Criteria andMakedtaeGreaterThan(Date value) {
            addCriterion("makeDtae >", value, "makedtae");
            return (Criteria) this;
        }

        public Criteria andMakedtaeGreaterThanOrEqualTo(Date value) {
            addCriterion("makeDtae >=", value, "makedtae");
            return (Criteria) this;
        }

        public Criteria andMakedtaeLessThan(Date value) {
            addCriterion("makeDtae <", value, "makedtae");
            return (Criteria) this;
        }

        public Criteria andMakedtaeLessThanOrEqualTo(Date value) {
            addCriterion("makeDtae <=", value, "makedtae");
            return (Criteria) this;
        }

        public Criteria andMakedtaeIn(List<Date> values) {
            addCriterion("makeDtae in", values, "makedtae");
            return (Criteria) this;
        }

        public Criteria andMakedtaeNotIn(List<Date> values) {
            addCriterion("makeDtae not in", values, "makedtae");
            return (Criteria) this;
        }

        public Criteria andMakedtaeBetween(Date value1, Date value2) {
            addCriterion("makeDtae between", value1, value2, "makedtae");
            return (Criteria) this;
        }

        public Criteria andMakedtaeNotBetween(Date value1, Date value2) {
            addCriterion("makeDtae not between", value1, value2, "makedtae");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("State is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("State is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("State =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("State <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("State >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("State >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("State <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("State <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("State like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("State not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("State in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("State not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("State between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("State not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("Comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("Comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("Comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("Comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("Comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("Comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("Comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("Comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("Comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("Comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("Comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("Comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("Comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("Comment not between", value1, value2, "comment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deliveryreceipt
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}