package com.lij.entity;

import java.util.ArrayList;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderID is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(String value) {
            addCriterion("orderID =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(String value) {
            addCriterion("orderID <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(String value) {
            addCriterion("orderID >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(String value) {
            addCriterion("orderID >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(String value) {
            addCriterion("orderID <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(String value) {
            addCriterion("orderID <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLike(String value) {
            addCriterion("orderID like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotLike(String value) {
            addCriterion("orderID not like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<String> values) {
            addCriterion("orderID in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<String> values) {
            addCriterion("orderID not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(String value1, String value2) {
            addCriterion("orderID between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(String value1, String value2) {
            addCriterion("orderID not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andCaridIsNull() {
            addCriterion("carID is null");
            return (Criteria) this;
        }

        public Criteria andCaridIsNotNull() {
            addCriterion("carID is not null");
            return (Criteria) this;
        }

        public Criteria andCaridEqualTo(String value) {
            addCriterion("carID =", value, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridNotEqualTo(String value) {
            addCriterion("carID <>", value, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridGreaterThan(String value) {
            addCriterion("carID >", value, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridGreaterThanOrEqualTo(String value) {
            addCriterion("carID >=", value, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridLessThan(String value) {
            addCriterion("carID <", value, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridLessThanOrEqualTo(String value) {
            addCriterion("carID <=", value, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridLike(String value) {
            addCriterion("carID like", value, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridNotLike(String value) {
            addCriterion("carID not like", value, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridIn(List<String> values) {
            addCriterion("carID in", values, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridNotIn(List<String> values) {
            addCriterion("carID not in", values, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridBetween(String value1, String value2) {
            addCriterion("carID between", value1, value2, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridNotBetween(String value1, String value2) {
            addCriterion("carID not between", value1, value2, "carid");
            return (Criteria) this;
        }

        public Criteria andCuidIsNull() {
            addCriterion("cuID is null");
            return (Criteria) this;
        }

        public Criteria andCuidIsNotNull() {
            addCriterion("cuID is not null");
            return (Criteria) this;
        }

        public Criteria andCuidEqualTo(String value) {
            addCriterion("cuID =", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidNotEqualTo(String value) {
            addCriterion("cuID <>", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidGreaterThan(String value) {
            addCriterion("cuID >", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidGreaterThanOrEqualTo(String value) {
            addCriterion("cuID >=", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidLessThan(String value) {
            addCriterion("cuID <", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidLessThanOrEqualTo(String value) {
            addCriterion("cuID <=", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidLike(String value) {
            addCriterion("cuID like", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidNotLike(String value) {
            addCriterion("cuID not like", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidIn(List<String> values) {
            addCriterion("cuID in", values, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidNotIn(List<String> values) {
            addCriterion("cuID not in", values, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidBetween(String value1, String value2) {
            addCriterion("cuID between", value1, value2, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidNotBetween(String value1, String value2) {
            addCriterion("cuID not between", value1, value2, "cuid");
            return (Criteria) this;
        }

        public Criteria andPostpnameIsNull() {
            addCriterion("postPName is null");
            return (Criteria) this;
        }

        public Criteria andPostpnameIsNotNull() {
            addCriterion("postPName is not null");
            return (Criteria) this;
        }

        public Criteria andPostpnameEqualTo(String value) {
            addCriterion("postPName =", value, "postpname");
            return (Criteria) this;
        }

        public Criteria andPostpnameNotEqualTo(String value) {
            addCriterion("postPName <>", value, "postpname");
            return (Criteria) this;
        }

        public Criteria andPostpnameGreaterThan(String value) {
            addCriterion("postPName >", value, "postpname");
            return (Criteria) this;
        }

        public Criteria andPostpnameGreaterThanOrEqualTo(String value) {
            addCriterion("postPName >=", value, "postpname");
            return (Criteria) this;
        }

        public Criteria andPostpnameLessThan(String value) {
            addCriterion("postPName <", value, "postpname");
            return (Criteria) this;
        }

        public Criteria andPostpnameLessThanOrEqualTo(String value) {
            addCriterion("postPName <=", value, "postpname");
            return (Criteria) this;
        }

        public Criteria andPostpnameLike(String value) {
            addCriterion("postPName like", value, "postpname");
            return (Criteria) this;
        }

        public Criteria andPostpnameNotLike(String value) {
            addCriterion("postPName not like", value, "postpname");
            return (Criteria) this;
        }

        public Criteria andPostpnameIn(List<String> values) {
            addCriterion("postPName in", values, "postpname");
            return (Criteria) this;
        }

        public Criteria andPostpnameNotIn(List<String> values) {
            addCriterion("postPName not in", values, "postpname");
            return (Criteria) this;
        }

        public Criteria andPostpnameBetween(String value1, String value2) {
            addCriterion("postPName between", value1, value2, "postpname");
            return (Criteria) this;
        }

        public Criteria andPostpnameNotBetween(String value1, String value2) {
            addCriterion("postPName not between", value1, value2, "postpname");
            return (Criteria) this;
        }

        public Criteria andPostptelIsNull() {
            addCriterion("postPTel is null");
            return (Criteria) this;
        }

        public Criteria andPostptelIsNotNull() {
            addCriterion("postPTel is not null");
            return (Criteria) this;
        }

        public Criteria andPostptelEqualTo(String value) {
            addCriterion("postPTel =", value, "postptel");
            return (Criteria) this;
        }

        public Criteria andPostptelNotEqualTo(String value) {
            addCriterion("postPTel <>", value, "postptel");
            return (Criteria) this;
        }

        public Criteria andPostptelGreaterThan(String value) {
            addCriterion("postPTel >", value, "postptel");
            return (Criteria) this;
        }

        public Criteria andPostptelGreaterThanOrEqualTo(String value) {
            addCriterion("postPTel >=", value, "postptel");
            return (Criteria) this;
        }

        public Criteria andPostptelLessThan(String value) {
            addCriterion("postPTel <", value, "postptel");
            return (Criteria) this;
        }

        public Criteria andPostptelLessThanOrEqualTo(String value) {
            addCriterion("postPTel <=", value, "postptel");
            return (Criteria) this;
        }

        public Criteria andPostptelLike(String value) {
            addCriterion("postPTel like", value, "postptel");
            return (Criteria) this;
        }

        public Criteria andPostptelNotLike(String value) {
            addCriterion("postPTel not like", value, "postptel");
            return (Criteria) this;
        }

        public Criteria andPostptelIn(List<String> values) {
            addCriterion("postPTel in", values, "postptel");
            return (Criteria) this;
        }

        public Criteria andPostptelNotIn(List<String> values) {
            addCriterion("postPTel not in", values, "postptel");
            return (Criteria) this;
        }

        public Criteria andPostptelBetween(String value1, String value2) {
            addCriterion("postPTel between", value1, value2, "postptel");
            return (Criteria) this;
        }

        public Criteria andPostptelNotBetween(String value1, String value2) {
            addCriterion("postPTel not between", value1, value2, "postptel");
            return (Criteria) this;
        }

        public Criteria andPostpaddrIsNull() {
            addCriterion("postPAddr is null");
            return (Criteria) this;
        }

        public Criteria andPostpaddrIsNotNull() {
            addCriterion("postPAddr is not null");
            return (Criteria) this;
        }

        public Criteria andPostpaddrEqualTo(String value) {
            addCriterion("postPAddr =", value, "postpaddr");
            return (Criteria) this;
        }

        public Criteria andPostpaddrNotEqualTo(String value) {
            addCriterion("postPAddr <>", value, "postpaddr");
            return (Criteria) this;
        }

        public Criteria andPostpaddrGreaterThan(String value) {
            addCriterion("postPAddr >", value, "postpaddr");
            return (Criteria) this;
        }

        public Criteria andPostpaddrGreaterThanOrEqualTo(String value) {
            addCriterion("postPAddr >=", value, "postpaddr");
            return (Criteria) this;
        }

        public Criteria andPostpaddrLessThan(String value) {
            addCriterion("postPAddr <", value, "postpaddr");
            return (Criteria) this;
        }

        public Criteria andPostpaddrLessThanOrEqualTo(String value) {
            addCriterion("postPAddr <=", value, "postpaddr");
            return (Criteria) this;
        }

        public Criteria andPostpaddrLike(String value) {
            addCriterion("postPAddr like", value, "postpaddr");
            return (Criteria) this;
        }

        public Criteria andPostpaddrNotLike(String value) {
            addCriterion("postPAddr not like", value, "postpaddr");
            return (Criteria) this;
        }

        public Criteria andPostpaddrIn(List<String> values) {
            addCriterion("postPAddr in", values, "postpaddr");
            return (Criteria) this;
        }

        public Criteria andPostpaddrNotIn(List<String> values) {
            addCriterion("postPAddr not in", values, "postpaddr");
            return (Criteria) this;
        }

        public Criteria andPostpaddrBetween(String value1, String value2) {
            addCriterion("postPAddr between", value1, value2, "postpaddr");
            return (Criteria) this;
        }

        public Criteria andPostpaddrNotBetween(String value1, String value2) {
            addCriterion("postPAddr not between", value1, value2, "postpaddr");
            return (Criteria) this;
        }

        public Criteria andGetpnameIsNull() {
            addCriterion("getPName is null");
            return (Criteria) this;
        }

        public Criteria andGetpnameIsNotNull() {
            addCriterion("getPName is not null");
            return (Criteria) this;
        }

        public Criteria andGetpnameEqualTo(String value) {
            addCriterion("getPName =", value, "getpname");
            return (Criteria) this;
        }

        public Criteria andGetpnameNotEqualTo(String value) {
            addCriterion("getPName <>", value, "getpname");
            return (Criteria) this;
        }

        public Criteria andGetpnameGreaterThan(String value) {
            addCriterion("getPName >", value, "getpname");
            return (Criteria) this;
        }

        public Criteria andGetpnameGreaterThanOrEqualTo(String value) {
            addCriterion("getPName >=", value, "getpname");
            return (Criteria) this;
        }

        public Criteria andGetpnameLessThan(String value) {
            addCriterion("getPName <", value, "getpname");
            return (Criteria) this;
        }

        public Criteria andGetpnameLessThanOrEqualTo(String value) {
            addCriterion("getPName <=", value, "getpname");
            return (Criteria) this;
        }

        public Criteria andGetpnameLike(String value) {
            addCriterion("getPName like", value, "getpname");
            return (Criteria) this;
        }

        public Criteria andGetpnameNotLike(String value) {
            addCriterion("getPName not like", value, "getpname");
            return (Criteria) this;
        }

        public Criteria andGetpnameIn(List<String> values) {
            addCriterion("getPName in", values, "getpname");
            return (Criteria) this;
        }

        public Criteria andGetpnameNotIn(List<String> values) {
            addCriterion("getPName not in", values, "getpname");
            return (Criteria) this;
        }

        public Criteria andGetpnameBetween(String value1, String value2) {
            addCriterion("getPName between", value1, value2, "getpname");
            return (Criteria) this;
        }

        public Criteria andGetpnameNotBetween(String value1, String value2) {
            addCriterion("getPName not between", value1, value2, "getpname");
            return (Criteria) this;
        }

        public Criteria andGetptelIsNull() {
            addCriterion("getPTel is null");
            return (Criteria) this;
        }

        public Criteria andGetptelIsNotNull() {
            addCriterion("getPTel is not null");
            return (Criteria) this;
        }

        public Criteria andGetptelEqualTo(String value) {
            addCriterion("getPTel =", value, "getptel");
            return (Criteria) this;
        }

        public Criteria andGetptelNotEqualTo(String value) {
            addCriterion("getPTel <>", value, "getptel");
            return (Criteria) this;
        }

        public Criteria andGetptelGreaterThan(String value) {
            addCriterion("getPTel >", value, "getptel");
            return (Criteria) this;
        }

        public Criteria andGetptelGreaterThanOrEqualTo(String value) {
            addCriterion("getPTel >=", value, "getptel");
            return (Criteria) this;
        }

        public Criteria andGetptelLessThan(String value) {
            addCriterion("getPTel <", value, "getptel");
            return (Criteria) this;
        }

        public Criteria andGetptelLessThanOrEqualTo(String value) {
            addCriterion("getPTel <=", value, "getptel");
            return (Criteria) this;
        }

        public Criteria andGetptelLike(String value) {
            addCriterion("getPTel like", value, "getptel");
            return (Criteria) this;
        }

        public Criteria andGetptelNotLike(String value) {
            addCriterion("getPTel not like", value, "getptel");
            return (Criteria) this;
        }

        public Criteria andGetptelIn(List<String> values) {
            addCriterion("getPTel in", values, "getptel");
            return (Criteria) this;
        }

        public Criteria andGetptelNotIn(List<String> values) {
            addCriterion("getPTel not in", values, "getptel");
            return (Criteria) this;
        }

        public Criteria andGetptelBetween(String value1, String value2) {
            addCriterion("getPTel between", value1, value2, "getptel");
            return (Criteria) this;
        }

        public Criteria andGetptelNotBetween(String value1, String value2) {
            addCriterion("getPTel not between", value1, value2, "getptel");
            return (Criteria) this;
        }

        public Criteria andGetpaddrIsNull() {
            addCriterion("getPAddr is null");
            return (Criteria) this;
        }

        public Criteria andGetpaddrIsNotNull() {
            addCriterion("getPAddr is not null");
            return (Criteria) this;
        }

        public Criteria andGetpaddrEqualTo(String value) {
            addCriterion("getPAddr =", value, "getpaddr");
            return (Criteria) this;
        }

        public Criteria andGetpaddrNotEqualTo(String value) {
            addCriterion("getPAddr <>", value, "getpaddr");
            return (Criteria) this;
        }

        public Criteria andGetpaddrGreaterThan(String value) {
            addCriterion("getPAddr >", value, "getpaddr");
            return (Criteria) this;
        }

        public Criteria andGetpaddrGreaterThanOrEqualTo(String value) {
            addCriterion("getPAddr >=", value, "getpaddr");
            return (Criteria) this;
        }

        public Criteria andGetpaddrLessThan(String value) {
            addCriterion("getPAddr <", value, "getpaddr");
            return (Criteria) this;
        }

        public Criteria andGetpaddrLessThanOrEqualTo(String value) {
            addCriterion("getPAddr <=", value, "getpaddr");
            return (Criteria) this;
        }

        public Criteria andGetpaddrLike(String value) {
            addCriterion("getPAddr like", value, "getpaddr");
            return (Criteria) this;
        }

        public Criteria andGetpaddrNotLike(String value) {
            addCriterion("getPAddr not like", value, "getpaddr");
            return (Criteria) this;
        }

        public Criteria andGetpaddrIn(List<String> values) {
            addCriterion("getPAddr in", values, "getpaddr");
            return (Criteria) this;
        }

        public Criteria andGetpaddrNotIn(List<String> values) {
            addCriterion("getPAddr not in", values, "getpaddr");
            return (Criteria) this;
        }

        public Criteria andGetpaddrBetween(String value1, String value2) {
            addCriterion("getPAddr between", value1, value2, "getpaddr");
            return (Criteria) this;
        }

        public Criteria andGetpaddrNotBetween(String value1, String value2) {
            addCriterion("getPAddr not between", value1, value2, "getpaddr");
            return (Criteria) this;
        }

        public Criteria andGoodsnameIsNull() {
            addCriterion("goodsName is null");
            return (Criteria) this;
        }

        public Criteria andGoodsnameIsNotNull() {
            addCriterion("goodsName is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsnameEqualTo(String value) {
            addCriterion("goodsName =", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotEqualTo(String value) {
            addCriterion("goodsName <>", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameGreaterThan(String value) {
            addCriterion("goodsName >", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameGreaterThanOrEqualTo(String value) {
            addCriterion("goodsName >=", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameLessThan(String value) {
            addCriterion("goodsName <", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameLessThanOrEqualTo(String value) {
            addCriterion("goodsName <=", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameLike(String value) {
            addCriterion("goodsName like", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotLike(String value) {
            addCriterion("goodsName not like", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameIn(List<String> values) {
            addCriterion("goodsName in", values, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotIn(List<String> values) {
            addCriterion("goodsName not in", values, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameBetween(String value1, String value2) {
            addCriterion("goodsName between", value1, value2, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotBetween(String value1, String value2) {
            addCriterion("goodsName not between", value1, value2, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsweightIsNull() {
            addCriterion("goodsWeight is null");
            return (Criteria) this;
        }

        public Criteria andGoodsweightIsNotNull() {
            addCriterion("goodsWeight is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsweightEqualTo(Integer value) {
            addCriterion("goodsWeight =", value, "goodsweight");
            return (Criteria) this;
        }

        public Criteria andGoodsweightNotEqualTo(Integer value) {
            addCriterion("goodsWeight <>", value, "goodsweight");
            return (Criteria) this;
        }

        public Criteria andGoodsweightGreaterThan(Integer value) {
            addCriterion("goodsWeight >", value, "goodsweight");
            return (Criteria) this;
        }

        public Criteria andGoodsweightGreaterThanOrEqualTo(Integer value) {
            addCriterion("goodsWeight >=", value, "goodsweight");
            return (Criteria) this;
        }

        public Criteria andGoodsweightLessThan(Integer value) {
            addCriterion("goodsWeight <", value, "goodsweight");
            return (Criteria) this;
        }

        public Criteria andGoodsweightLessThanOrEqualTo(Integer value) {
            addCriterion("goodsWeight <=", value, "goodsweight");
            return (Criteria) this;
        }

        public Criteria andGoodsweightIn(List<Integer> values) {
            addCriterion("goodsWeight in", values, "goodsweight");
            return (Criteria) this;
        }

        public Criteria andGoodsweightNotIn(List<Integer> values) {
            addCriterion("goodsWeight not in", values, "goodsweight");
            return (Criteria) this;
        }

        public Criteria andGoodsweightBetween(Integer value1, Integer value2) {
            addCriterion("goodsWeight between", value1, value2, "goodsweight");
            return (Criteria) this;
        }

        public Criteria andGoodsweightNotBetween(Integer value1, Integer value2) {
            addCriterion("goodsWeight not between", value1, value2, "goodsweight");
            return (Criteria) this;
        }

        public Criteria andOrdertypeIsNull() {
            addCriterion("orderType is null");
            return (Criteria) this;
        }

        public Criteria andOrdertypeIsNotNull() {
            addCriterion("orderType is not null");
            return (Criteria) this;
        }

        public Criteria andOrdertypeEqualTo(String value) {
            addCriterion("orderType =", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeNotEqualTo(String value) {
            addCriterion("orderType <>", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeGreaterThan(String value) {
            addCriterion("orderType >", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeGreaterThanOrEqualTo(String value) {
            addCriterion("orderType >=", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeLessThan(String value) {
            addCriterion("orderType <", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeLessThanOrEqualTo(String value) {
            addCriterion("orderType <=", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeLike(String value) {
            addCriterion("orderType like", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeNotLike(String value) {
            addCriterion("orderType not like", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeIn(List<String> values) {
            addCriterion("orderType in", values, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeNotIn(List<String> values) {
            addCriterion("orderType not in", values, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeBetween(String value1, String value2) {
            addCriterion("orderType between", value1, value2, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeNotBetween(String value1, String value2) {
            addCriterion("orderType not between", value1, value2, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrderstateIsNull() {
            addCriterion("orderState is null");
            return (Criteria) this;
        }

        public Criteria andOrderstateIsNotNull() {
            addCriterion("orderState is not null");
            return (Criteria) this;
        }

        public Criteria andOrderstateEqualTo(String value) {
            addCriterion("orderState =", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotEqualTo(String value) {
            addCriterion("orderState <>", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateGreaterThan(String value) {
            addCriterion("orderState >", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateGreaterThanOrEqualTo(String value) {
            addCriterion("orderState >=", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateLessThan(String value) {
            addCriterion("orderState <", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateLessThanOrEqualTo(String value) {
            addCriterion("orderState <=", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateLike(String value) {
            addCriterion("orderState like", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotLike(String value) {
            addCriterion("orderState not like", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateIn(List<String> values) {
            addCriterion("orderState in", values, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotIn(List<String> values) {
            addCriterion("orderState not in", values, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateBetween(String value1, String value2) {
            addCriterion("orderState between", value1, value2, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotBetween(String value1, String value2) {
            addCriterion("orderState not between", value1, value2, "orderstate");
            return (Criteria) this;
        }

        public Criteria andTrdnsportpriceIsNull() {
            addCriterion("trdnsportPrice is null");
            return (Criteria) this;
        }

        public Criteria andTrdnsportpriceIsNotNull() {
            addCriterion("trdnsportPrice is not null");
            return (Criteria) this;
        }

        public Criteria andTrdnsportpriceEqualTo(Long value) {
            addCriterion("trdnsportPrice =", value, "trdnsportprice");
            return (Criteria) this;
        }

        public Criteria andTrdnsportpriceNotEqualTo(Long value) {
            addCriterion("trdnsportPrice <>", value, "trdnsportprice");
            return (Criteria) this;
        }

        public Criteria andTrdnsportpriceGreaterThan(Long value) {
            addCriterion("trdnsportPrice >", value, "trdnsportprice");
            return (Criteria) this;
        }

        public Criteria andTrdnsportpriceGreaterThanOrEqualTo(Long value) {
            addCriterion("trdnsportPrice >=", value, "trdnsportprice");
            return (Criteria) this;
        }

        public Criteria andTrdnsportpriceLessThan(Long value) {
            addCriterion("trdnsportPrice <", value, "trdnsportprice");
            return (Criteria) this;
        }

        public Criteria andTrdnsportpriceLessThanOrEqualTo(Long value) {
            addCriterion("trdnsportPrice <=", value, "trdnsportprice");
            return (Criteria) this;
        }

        public Criteria andTrdnsportpriceIn(List<Long> values) {
            addCriterion("trdnsportPrice in", values, "trdnsportprice");
            return (Criteria) this;
        }

        public Criteria andTrdnsportpriceNotIn(List<Long> values) {
            addCriterion("trdnsportPrice not in", values, "trdnsportprice");
            return (Criteria) this;
        }

        public Criteria andTrdnsportpriceBetween(Long value1, Long value2) {
            addCriterion("trdnsportPrice between", value1, value2, "trdnsportprice");
            return (Criteria) this;
        }

        public Criteria andTrdnsportpriceNotBetween(Long value1, Long value2) {
            addCriterion("trdnsportPrice not between", value1, value2, "trdnsportprice");
            return (Criteria) this;
        }

        public Criteria andDeliverypriceIsNull() {
            addCriterion("deliveryPrice is null");
            return (Criteria) this;
        }

        public Criteria andDeliverypriceIsNotNull() {
            addCriterion("deliveryPrice is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverypriceEqualTo(Long value) {
            addCriterion("deliveryPrice =", value, "deliveryprice");
            return (Criteria) this;
        }

        public Criteria andDeliverypriceNotEqualTo(Long value) {
            addCriterion("deliveryPrice <>", value, "deliveryprice");
            return (Criteria) this;
        }

        public Criteria andDeliverypriceGreaterThan(Long value) {
            addCriterion("deliveryPrice >", value, "deliveryprice");
            return (Criteria) this;
        }

        public Criteria andDeliverypriceGreaterThanOrEqualTo(Long value) {
            addCriterion("deliveryPrice >=", value, "deliveryprice");
            return (Criteria) this;
        }

        public Criteria andDeliverypriceLessThan(Long value) {
            addCriterion("deliveryPrice <", value, "deliveryprice");
            return (Criteria) this;
        }

        public Criteria andDeliverypriceLessThanOrEqualTo(Long value) {
            addCriterion("deliveryPrice <=", value, "deliveryprice");
            return (Criteria) this;
        }

        public Criteria andDeliverypriceIn(List<Long> values) {
            addCriterion("deliveryPrice in", values, "deliveryprice");
            return (Criteria) this;
        }

        public Criteria andDeliverypriceNotIn(List<Long> values) {
            addCriterion("deliveryPrice not in", values, "deliveryprice");
            return (Criteria) this;
        }

        public Criteria andDeliverypriceBetween(Long value1, Long value2) {
            addCriterion("deliveryPrice between", value1, value2, "deliveryprice");
            return (Criteria) this;
        }

        public Criteria andDeliverypriceNotBetween(Long value1, Long value2) {
            addCriterion("deliveryPrice not between", value1, value2, "deliveryprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceIsNull() {
            addCriterion("totalPrice is null");
            return (Criteria) this;
        }

        public Criteria andTotalpriceIsNotNull() {
            addCriterion("totalPrice is not null");
            return (Criteria) this;
        }

        public Criteria andTotalpriceEqualTo(String value) {
            addCriterion("totalPrice =", value, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceNotEqualTo(String value) {
            addCriterion("totalPrice <>", value, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceGreaterThan(String value) {
            addCriterion("totalPrice >", value, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceGreaterThanOrEqualTo(String value) {
            addCriterion("totalPrice >=", value, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceLessThan(String value) {
            addCriterion("totalPrice <", value, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceLessThanOrEqualTo(String value) {
            addCriterion("totalPrice <=", value, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceLike(String value) {
            addCriterion("totalPrice like", value, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceNotLike(String value) {
            addCriterion("totalPrice not like", value, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceIn(List<String> values) {
            addCriterion("totalPrice in", values, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceNotIn(List<String> values) {
            addCriterion("totalPrice not in", values, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceBetween(String value1, String value2) {
            addCriterion("totalPrice between", value1, value2, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceNotBetween(String value1, String value2) {
            addCriterion("totalPrice not between", value1, value2, "totalprice");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("Comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("Comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("Comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("Comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("Comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("Comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("Comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("Comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("Comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("Comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("Comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("Comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("Comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("Comment not between", value1, value2, "comment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}